DEFINE DATABASE ROLE {{db}}.ADMIN
    COMMENT = 'Full control: DDL + DML - {{env}}';

DEFINE DATABASE ROLE {{db}}.DEVELOPER
    COMMENT = 'Read/write: DML only - {{env}}';

DEFINE DATABASE ROLE {{db}}.ANALYST
    COMMENT = 'Read-only: SELECT only - {{env}}';

DEFINE ROLE GITOPS_WH_USER{{env_suffix}}
    COMMENT = 'Warehouse access for GitOps project - {{env}}';

GRANT DATABASE ROLE {{db}}.ANALYST TO DATABASE ROLE {{db}}.DEVELOPER;
GRANT DATABASE ROLE {{db}}.DEVELOPER TO DATABASE ROLE {{db}}.ADMIN;
GRANT DATABASE ROLE {{db}}.ADMIN TO ROLE SYSADMIN;
GRANT ROLE GITOPS_WH_USER{{env_suffix}} TO ROLE SYSADMIN;

GRANT USAGE ON WAREHOUSE GITOPS_WH{{env_suffix}} TO ROLE GITOPS_WH_USER{{env_suffix}};

GRANT USAGE ON DATABASE {{db}} TO DATABASE ROLE {{db}}.ANALYST;

GRANT USAGE ON SCHEMA {{db}}.RAW TO DATABASE ROLE {{db}}.ANALYST;
GRANT USAGE ON SCHEMA {{db}}.ANALYTICS TO DATABASE ROLE {{db}}.ANALYST;
GRANT USAGE ON SCHEMA {{db}}.SERVE TO DATABASE ROLE {{db}}.ANALYST;

GRANT SELECT ON ALL TABLES IN SCHEMA {{db}}.RAW TO DATABASE ROLE {{db}}.ANALYST;
GRANT SELECT ON ALL VIEWS IN SCHEMA {{db}}.SERVE TO DATABASE ROLE {{db}}.ANALYST;
GRANT SELECT ON ALL DYNAMIC TABLES IN SCHEMA {{db}}.ANALYTICS TO DATABASE ROLE {{db}}.ANALYST;

GRANT INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA {{db}}.RAW TO DATABASE ROLE {{db}}.DEVELOPER;

GRANT CREATE TABLE, CREATE VIEW, CREATE DYNAMIC TABLE
    ON SCHEMA {{db}}.RAW TO DATABASE ROLE {{db}}.ADMIN;
GRANT CREATE TABLE, CREATE VIEW, CREATE DYNAMIC TABLE
    ON SCHEMA {{db}}.ANALYTICS TO DATABASE ROLE {{db}}.ADMIN;
GRANT CREATE TABLE, CREATE VIEW, CREATE DYNAMIC TABLE
    ON SCHEMA {{db}}.SERVE TO DATABASE ROLE {{db}}.ADMIN;
