DEFINE DYNAMIC TABLE {{db}}.ANALYTICS.DT_CUSTOMER_ORDERS
WAREHOUSE = 'GITOPS_WH{{env_suffix}}'
TARGET_LAG = '{{dt_lag}}'
INITIALIZE = 'ON_CREATE'
AS
SELECT
    c.CUSTOMER_ID,
    c.FIRST_NAME,
    c.LAST_NAME,
    c.EMAIL,
    c.REGION,
    COUNT(DISTINCT o.ORDER_ID) AS TOTAL_ORDERS,
    SUM(o.TOTAL_AMOUNT) AS TOTAL_SPEND,
    MIN(o.ORDER_DATE) AS FIRST_ORDER_DATE,
    MAX(o.ORDER_DATE) AS LAST_ORDER_DATE,
    CASE WHEN COUNT(DISTINCT o.ORDER_ID) > 0 THEN SUM(o.TOTAL_AMOUNT) / COUNT(DISTINCT o.ORDER_ID) ELSE 0 END AS AVG_ORDER_VALUE,
    DATEDIFF('DAY', MAX(o.ORDER_DATE), CURRENT_DATE()) AS DAYS_SINCE_LAST_ORDER,
    c.LOYALTY_TIER
FROM {{db}}.RAW.CUSTOMERS c
LEFT JOIN {{db}}.RAW.ORDERS o ON c.CUSTOMER_ID = o.CUSTOMER_ID
GROUP BY c.CUSTOMER_ID, c.FIRST_NAME, c.LAST_NAME, c.EMAIL, c.REGION, c.LOYALTY_TIER;

DEFINE DYNAMIC TABLE {{db}}.ANALYTICS.DT_DAILY_REVENUE
WAREHOUSE = 'GITOPS_WH{{env_suffix}}'
TARGET_LAG = '{{dt_lag}}'
INITIALIZE = 'ON_CREATE'
AS
SELECT
    DATE_TRUNC('DAY', o.ORDER_DATE) AS ORDER_DAY,
    p.CATEGORY,
    COUNT(DISTINCT o.ORDER_ID) AS ORDER_COUNT,
    SUM(o.TOTAL_AMOUNT) AS DAILY_REVENUE,
    CASE WHEN COUNT(DISTINCT o.ORDER_ID) > 0 THEN SUM(o.TOTAL_AMOUNT) / COUNT(DISTINCT o.ORDER_ID) ELSE 0 END AS AVG_ORDER_VALUE,
    MAX(o.TOTAL_AMOUNT) AS MAX_ORDER_AMOUNT
FROM {{db}}.RAW.ORDERS o
LEFT JOIN {{db}}.RAW.PRODUCTS p ON o.CUSTOMER_ID = p.PRODUCT_ID
WHERE o.STATUS != 'CANCELLED'
GROUP BY ORDER_DAY, p.CATEGORY;
