-- Data quality expectations: null checks and duplicate detection
ATTACH DATA METRIC FUNCTION SNOWFLAKE.CORE.NULL_COUNT
    TO TABLE {{db}}.RAW.CUSTOMERS
    ON (CUSTOMER_ID)
    EXPECTATION NO_NULL_CUSTOMER_IDS (value = 0);

ATTACH DATA METRIC FUNCTION SNOWFLAKE.CORE.DUPLICATE_COUNT
    TO TABLE {{db}}.RAW.CUSTOMERS
    ON (EMAIL)
    EXPECTATION NO_DUPLICATE_EMAILS (value = 0);

ATTACH DATA METRIC FUNCTION SNOWFLAKE.CORE.NULL_COUNT
    TO TABLE {{db}}.RAW.ORDERS
    ON (ORDER_ID)
    EXPECTATION NO_NULL_ORDER_IDS (value = 0);

ATTACH DATA METRIC FUNCTION SNOWFLAKE.CORE.NULL_COUNT
    TO TABLE {{db}}.RAW.ORDERS
    ON (CUSTOMER_ID)
    EXPECTATION NO_NULL_ORDER_CUSTOMER_IDS (value = 0);

ATTACH DATA METRIC FUNCTION SNOWFLAKE.CORE.NULL_COUNT
    TO TABLE {{db}}.RAW.PRODUCTS
    ON (PRODUCT_ID)
    EXPECTATION NO_NULL_PRODUCT_IDS (value = 0);
