DEFINE VIEW {{db}}.SERVE.V_CUSTOMER_360
AS
SELECT
    CUSTOMER_ID,
    FIRST_NAME,
    LAST_NAME,
    EMAIL,
    REGION,
    TOTAL_ORDERS,
    TOTAL_SPEND,
    FIRST_ORDER_DATE,
    LAST_ORDER_DATE,
    AVG_ORDER_VALUE,
    DAYS_SINCE_LAST_ORDER,
    LOYALTY_TIER
FROM {{db}}.ANALYTICS.DT_CUSTOMER_ORDERS
WHERE TOTAL_ORDERS > 0;

DEFINE VIEW {{db}}.SERVE.V_DAILY_REVENUE_SUMMARY
DATA_METRIC_SCHEDULE = 'USING CRON 0 7 * * * UTC'
AS
SELECT
    ORDER_DAY,
    CATEGORY,
    ORDER_COUNT,
    DAILY_REVENUE,
    AVG_ORDER_VALUE
FROM {{db}}.ANALYTICS.DT_DAILY_REVENUE
WHERE ORDER_DAY >= DATEADD('DAY', -30, CURRENT_DATE());

DEFINE VIEW {{db}}.SERVE.V_ACTIVE_PRODUCTS
AS
SELECT
    PRODUCT_ID,
    PRODUCT_NAME,
    CATEGORY,
    UNIT_PRICE,
    SKU,
    STOCK_QUANTITY
FROM {{db}}.RAW.PRODUCTS
WHERE IS_ACTIVE = TRUE;
